### ISSUE TITLE
Auto-Refresh

### ISSUE THREAD

**Issue by homes32** [bemace/SpotterLevel3#58]
Feature Request: 
User configurable auto-refresh interval

Allow the user to define a refresh interval (min/sec) to automatically poll the APRS data. Don't forget, the APRS.fi API rate limits requests, so it may be useful to include some help/text to warn the user against setting aggressive refresh intervals. The UI should also show the timestamp of the last refresh, or even better, a countdown to the next refresh, similar to how GRLevel3 shows a countdown in the lower right corner.

**Comment by bemace** [comment]
I think I took care of this in #12 , although I see that's maybe not as clear as it could be in the UI.  In my local version at least, there's an Auto-Update interval field in the settings. But that's a rate-limiter/ *minimum* interval, with updates only being triggered when when GRL3 requests an updated datafile. (in accordance with aprs.fi terms)
